env:
  browser: true
  es2021: true

extends:
  - plugin:react/recommended
  - airbnb
overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

rules:
  import/extensions: 0
  react/react-in-jsx-scope: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  no-console: 0
